version: '3.8'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: '${PASSWORD}'
      MYSQL_DATABASE: '${DATABASE}'
      MYSQL_USER: '${USER}'
      MYSQL_PASSWORD: '${PASSWORD}'
    volumes:
      - database:/var/lib/mysql
    networks:
      - wordpress-network

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: '${USER}'
      WORDPRESS_DB_PASSWORD: '${PASSWORD}'
      WORDPRESS_DB_NAME: '${DATABASE}'
    volumes:
      - ./wp-content/:/var/www/html/wp-content
      - wordpress:/var/www/html
    networks:
      - wordpress-network

volumes:
  database:
  wordpress:

networks:
  wordpress-network: